name: toy_box
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  intl: ^0.18.0
  url_launcher: ^6.1.8
  shared_preferences: ^2.0.17
  flutter_facebook_auth: ^5.0.7
  twitter_login: ^4.3.1
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
      - asset: assets/fonts/Nunito/Nunito-Regular.ttf
      - asset: assets/fonts/Nunito/Nunito-Light.ttf
        weight: 100
      - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        weight: 300
      - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        weight: 500

  assets:
    - assets/images/